### ISSUE TITLE
Imported text files do not inherit formatting.

### ISSUE THREAD

**Issue by owlsketch** [owlsketch/swipe-file#6]
No newline, no tabbing.

**Comment by helensee** [comment]
Plain text file keeps format, but there's a random space above div, need to remove it

**Comment by helensee** [comment]
removed random spacing that is part of < pre > css, need to fix formatting if text file is a very long and single lined

**Comment by owlsketch** [comment]
https://perishablepress.com/perfect-pre-tags/
This will definitely help with the text formatting.

**Comment by owlsketch** [comment]
See updated version. Newline indentation is still whack yo.

**Comment by owlsketch** [comment]
This issue is technically fixed, since the newline issue can be by itself, I will be closing this.
